### ISSUE TITLE
Add --create-bam for running cellranger 8.0.0

### ISSUE THREAD

**Issue by PT806** [chunjie-sam-liu/scMOCHA#11]
Hi, when I use Cellranger 8.0.0 to test my 10X Genomics V4 chemistry, I found that we should add another parameter --create-bam (true | false) to our .json file and .wdl file in order to let users use cellranger8.0.0 smoothly  for V4 dataset.

**Comment by chunjie-sam-liu** [comment]
Add the [line](https://github.com/chunjie-sam-liu/scMOCHA/blob/2804f7bcbb9c4c881f63d687417ccb9eff5f5308/scMOCHA.wdl#L393) for 10x v4.
