### ISSUE TITLE
error in scMOCHA.R

### ISSUE THREAD

**Issue by PT806** [chunjie-sam-liu/scMOCHA#4]
line631 of /bin/scMOCHA.R, the path of user's anaconda3 may be not in ~/tools/anaconda3, for mine is: ~/anaconda3. Thus, when I use your code, it occurs the error: No such error or directory.

**Comment by chunjie-sam-liu** [comment]
This question is the same with #5 , I modify the scMOCHA.R and make this to input the directory.
