### ISSUE TITLE
error in scMOCHA.wdl

### ISSUE THREAD

**Issue by PT806** [chunjie-sam-liu/scMOCHA#5]
line46, File jar_path should be  "/scr1/users/liuc9/tools/haplogrep3"  not "/scr1/users/liuc9/tools/haplogrep3/haplogrep3.jar" , or it will occur errors when running line631 of scMOCHA.R.

**Comment by chunjie-sam-liu** [comment]
it should be /scr1/users/liuc9/tools/haplogrep3
